/** RPC commands registered by the current verged core, wallet, and SMSG modules. */
export const RPC_COMMANDS = [
	'abandontransaction',
	'abortrescan',
	'addmultisigaddress',
	'addnode',
	'addwitnessaddress',
	'backupwallet',
	'bumpfee',
	'clearbanned',
	'combinerawtransaction',
	'createbond',
	'createmultisig',
	'createrawtransaction',
	'createwallet',
	'debuginfo',
	'decodeblock',
	'decoderawtransaction',
	'decodescript',
	'disconnectnode',
	'dumpprivkey',
	'dumpwallet',
	'echo',
	'echojson',
	'encryptwallet',
	'estimatefee',
	'estimaterawfee',
	'estimatesmartfee',
	'exportstealthaddress',
	'flushsmgsdb',
	'fundrawtransaction',
	'generate',
	'generatestake',
	'generatetoaddress',
	'getaccount',
	'getaccountaddress',
	'getaddednodeinfo',
	'getaddressesbyaccount',
	'getaddressesbylabel',
	'getaddressinfo',
	'getallnetworkhashps',
	'getbalance',
	'getbestblockhash',
	'getblock',
	'getblockchaininfo',
	'getblockcount',
	'getblockhash',
	'getblockheader',
	'getblockstats',
	'getblocktemplate',
	'getchaintips',
	'getchaintxstats',
	'getconnectioncount',
	'getdifficulty',
	'getinfo',
	'getmemoryinfo',
	'getmempoolancestors',
	'getmempooldescendants',
	'getmempoolentry',
	'getmempoolinfo',
	'getmininginfo',
	'getnettotals',
	'getnetworkhashps',
	'getnetworkinfo',
	'getnewaddress',
	'getnewstealthaddress',
	'getnodeaddresses',
	'getpeerinfo',
	'getrawchangeaddress',
	'getrawmempool',
	'getrawtransaction',
	'getreceivedbyaccount',
	'getreceivedbyaddress',
	'getreceivedbylabel',
	'getstakinginfo',
	'gettransaction',
	'gettxout',
	'gettxoutproof',
	'gettxoutsetinfo',
	'getunconfirmedbalance',
	'getwalletinfo',
	'help',
	'importaddress',
	'importmulti',
	'importprivkey',
	'importprunedfunds',
	'importpubkey',
	'importstealthaddress',
	'importwallet',
	'invalidateblock',
	'keypoolrefill',
	'listaccounts',
	'listaddressgroupings',
	'listbanned',
	'listlabels',
	'listlockunspent',
	'listreceivedbyaccount',
	'listreceivedbyaddress',
	'listreceivedbylabel',
	'listsinceblock',
	'liststealthaddresses',
	'listtransactions',
	'listunspent',
	'listwallets',
	'loadwallet',
	'lockunspent',
	'logging',
	'move',
	'ping',
	'preciousblock',
	'prioritisetransaction',
	'pruneblockchain',
	'reconsiderblock',
	'removeprunedfunds',
	'rescanblockchain',
	'resendwallettransactions',
	'reserializeblock',
	'savemempool',
	'sendfrom',
	'sendmany',
	'sendrawtransaction',
	'sendtoaddress',
	'sendtostealthaddress',
	'setaccount',
	'setalgo',
	'setban',
	'sethdseed',
	'setlabel',
	'setmocktime',
	'setnetworkactive',
	'setstaking',
	'settxfee',
	'signmessage',
	'signmessagewithprivkey',
	'signrawtransaction',
	'signrawtransactionwithkey',
	'signrawtransactionwithwallet',
	'smsg',
	'smsgaddaddress',
	'smsgaddlocaladdress',
	'smsgbuckets',
	'smsgdisable',
	'smsgenable',
	'smsggetpubkey',
	'smsgimportprivkey',
	'smsginbox',
	'smsginfo',
	'smsglocalkeys',
	'smsgoptions',
	'smsgoutbox',
	'smsgpurge',
	'smsgscanbuckets',
	'smsgscanchain',
	'smsgsend',
	'smsgsendanon',
	'smsgview',
	'stop',
	'submitblock',
	'syncwithvalidationinterfacequeue',
	'testmempoolaccept',
	'unbond',
	'uptime',
	'validateaddress',
	'verifychain',
	'verifymessage',
	'verifytxoutproof',
	'waitforblock',
	'waitforblockheight',
	'waitfornewblock',
	'walletlock',
	'walletpassphrase',
	'walletpassphrasechange',
] as const

export type RPCCommand = (typeof RPC_COMMANDS)[number]

export abstract class API {
	readonly commands: readonly RPCCommand[] = RPC_COMMANDS

	isCommand(command: string): boolean {
		return (RPC_COMMANDS as readonly string[]).includes(command.toLowerCase())
	}

	getCommands(): readonly RPCCommand[] {
		return this.commands
	}

	abstract call<Result = unknown>(
		command: RPCCommand,
		...params: unknown[]
	): Promise<Result>
}
